import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";

import Navigation from "@/components/Navigation";
import Login from "@/components/auth/Login";
import Statistics from "@/components/Statistics";
import Search from "@/components/Search";
import { useRouter } from "next/router";
import { Suspense, useEffect } from "react";
import Data from "@/components/Data";

const Home: NextPage = () => {
  const { data } = useSession();
  const router = useRouter();

  useEffect(() => {
    console.log(!data?.user);
    if (!data?.user) {
      router.push("/login");
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Suspense fallback="Loading..">
        <main className="">
          <div className="align-items-center grid p-8 ">
            <div className="mx-auto grid w-full p-4 opacity-80 sm:w-3/4">
              <Statistics />
              <Search />
              <Data />
            </div>
          </div>
        </main>
      </Suspense>
    </>
  );
};

export default Home;
